name: Docker Compose Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate to AWS
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Build Docker Image
        run: docker build -t dot-hack .

      - name: Tag and Push Docker Image
        run: |
          docker tag dot-hack:latest ${{ secrets.AWS_ECR_REGISTRY }}/dot-hack:latest
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/dot-hack:latest

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init --platform Docker --region ${{ secrets.AWS_DEFAULT_REGION }}
          eb create Telegram-bot-env --single --instance-type t2.micro
          eb deploy

